def import_pods
    pod 'lowladb-objc', :path => '../../'
    pod 'liblowladb', :path => "../../../liblowladb"
end

target :ios do
    platform :ios, '7.0'
    link_with 'LowlaDBiOSFramework'
    import_pods
end

target :osx do
    platform :osx, '10.9'
    link_with 'LowlaDBFramework'
    import_pods
end